### PR TITLE
Day2 Jingmiao

### PR DESCRIPTION
**Pull request by Jasmine-404**
## Checklist

- [ ] You have included a thumbnail image
- [ ] You have created a new Markdown file to describe your map
- [ ] You have put _at least_ your name and the map day in the pull request

### CODE REVIEW

**Comment by Jasmine-404** [comment]
Sorry I accidentally clicked “Merge branch 'weitzman-musa:main' into main”! I don't know if this will have any impact... TT

**Review by mjumbewu — APPROVED** [review]
👍🏽

**Comment by mjumbewu** [comment]
@Jasmine-404 btw, I think this map is really beautiful.

**Comment by Jasmine-404** [comment]
> @Jasmine-404 btw, I think this map is really beautiful.

@mjumbewu Thank you so much Mjumbe!! I spent a lot of time choosing colors and adjusting the layout. So I'm really glad that you like it!!

**Pull request merged**
