### PR TITLE
13_skhare

### PR DESCRIPTION
**Pull request by samriddhikhar3**
## Checklist

- [x] You have included a thumbnail image
- [x] You have created a new Markdown file to describe your map
- [x] You have put _at least_ your name and the map day in the pull request

### CODE REVIEW

**Review by mjumbewu — COMMENTED** [review]
@samriddhikhar3 these maps are looking great! Do you have links to the source code that you used to generate them?

**Comment by samriddhikhar3** [comment]
> @samriddhikhar3 these maps are looking great! Do you have links to the source code that you used to generate them?

Thanks Mjumbe! I'll add the source code in a bit. One note though: some of these maps were made in arcGIS so I'll be uploading the R data processing script for those.

**Comment by mjumbewu** [comment]
> > @samriddhikhar3 these maps are looking great! Do you have links to the source code that you used to generate them?
> 
> Thanks Mjumbe! I'll add the source code in a bit. One note though: some of these maps were made in arcGIS so I'll be uploading the R data processing script for those.

:+1: Sounds great!

**Comment by mjumbewu** [comment]
@samriddhikhar3 I see those source URLs; excellent! LGTM (looks good to me)

**Pull request merged**
